### ISSUE TITLE
Romans 01 to 16 seem to have no text

### ISSUE THREAD

**Issue by DavidHaslam** [lb42/KJV_1611#1]
The 16 chapter files **Romans_##.xml** seem to be devoid of verse text.

They simply have the **div** element and nothing inside it.

**Comment by lb42** [comment]
Oh expletive deleted. I thought I'd caught all those. Will check.

**Comment by DavidHaslam** [comment]
Easily done. It became apparent when I did a directory sort in reverse file size order.

**Comment by lb42** [comment]
OK, I have tracked down and restored the wandering Romans. They were missing due to an embarassingly stupid error in my work/grab script

**Comment by DavidHaslam** [comment]
Thanks. Don't be so hard on yourself. 
These things happen to others (including myself) far more often than we imagine.
Glad to have been of some small service in the road to recovering the wanderers. :)
