### ISSUE TITLE
Canonical Psalm titles

### ISSUE THREAD

**Issue by DavidHaslam** [lb42/KJV_1611#10]
These currently use the TEI **head** element.

Currently there is no XML attribute that would distinguish the 116 **canonical** Psalm titles from the noncanonical descriptions at the start of other chapters.

These canonical Psalm titles in the KJV correspond to those in the Hebrew text.

**Comment by lb42** [comment]
I am now thinking it might be better to tag the "noncanonical descriptions" (the summaries at the starts of other chapters) with something other than `<head>` e.g. `<opener>`. The titles of the Psalms really are `<head>`s though: could add a @type='title' vel sim maybe to distinguish from the `<head>` containing their number ("Psalm 12")

**Comment by DavidHaslam** [comment]
If TEI permits that and it seems appropriate, then go for it.

In OSIS also, `<abbr expansion="Chapter">CHAP.</abbr>` would be appropriate inside the head element.

These titles are best thought of as "chapter label", and correspond to the USFM tag `\cl `

Then there's the thorny question of Roman numerals.

Should we apply any particular XML markup to these chapter numbers?

It might be thought of as cheating to use the **abbr** element in OSIS for this purpose,
yet it's a kludge that could be helpful.

`<abbr expansion="119">CXIX</abbr>.`

**Comment by lb42** [comment]
Cf discussion and fix reported on issue #4 : I don't think "CXIX" is an abbreviation for "119" : they are just different ways of writing the same thing. In TEI you could do this with `<num value="119">CXIX</num>` if you wanted, but it seems a bit pointless to me.

**Comment by DavidHaslam** [comment]
Not so pointless if for downstream uses that could save developers the chore of converting Roman numerals to decimal.

I agree, it's not truly an abbreviation, but OSIS had no equivalent to `<num value="119">CXIX</num>`.

Maybe that's an enhancement to propose, at least for use within [CrossWire](https://crosswire.org/wiki/OSIS_211_CR) ?

**Comment by lb42** [comment]
There are other more reliable ways of finding the number of a chapter than translating the roman number! e.g. <xsl:number/> . It could also be supplied by means of an @n attribute, as I do for the verses.
