### ISSUE TITLE
FIO. The KJV 1611 at Original Bibles 

### ISSUE THREAD

**Issue by DavidHaslam** [lb42/KJV_1611#16]
Facsimile page images for the **KJV 1611** are also available at [Original Bibles](https://www.originalbibles.com/the-original-king-james-bible-1611-pdf/).

The images are in PDF format. Navigation is somewhat awkward.

Many other historic Bibles are available on the same site.

**Comment by DavidHaslam** [comment]
Worth having a second source for checking if anything is still illegible in the primary source.

**Comment by lb42** [comment]
Thanks for the link. I think I found it once before when I was looking for versions of the front matter, which is missing from the transcript.
