### ISSUE TITLE
Parentheses

### ISSUE THREAD

**Issue by DavidHaslam** [lb42/KJV_1611#8]
I noticed that there is a mismatch in the number of left and right parentheses:
```
U+0028	(	664	LEFT PARENTHESIS
U+0029	)	662	RIGHT PARENTHESIS
```
At least 2 must be unpaired. Further analysis showed that there are only 2 such locations:
```
<ab n="1">Now the sonnes of Reuben the first borne of Israel, (for hee was the first borne, but, forasmuch as he defiled his fathers bed, his birthright was giuen vnto the sonnes of Ioseph the sonne of Israel: and the genealogie is not to be reckoned after the birthright.<note> Gen. 35. 22.and 49. 4.</note></ab>
<ab n="13">(For not the hearers of the Law are iust before God, but the doers of the Law shalbe iustified;</ab>
```

The respective locations are:
- **1 Chronicles 5:1**
- **Romans 2:13**

**Comment by lb42** [comment]
The closing parenthesis is missing from the original source in both cases, so I don't consider this to be an issue.

**Comment by DavidHaslam** [comment]
Fair enough. It's still an intriguing phenomenon though.

Aside: There are places in the 1611 edition that has text in parentheses where modern editions don't.
Probably vice versa too, though I've not checked.

One such example is **Romans 1:10**
```
<ab n="10">Making request, (if by any meanes now at length I might haue a prosperous iourney by the will of God) to come vnto you.</ab>
```

**Comment by DavidHaslam** [comment]
Did you also check the `)` was missing in the page images? @lb42 

Just wondering if this was rather an upstream error in the source website HTML ....

**Comment by lb42** [comment]
Yes. When I say "original source" I mean the page images. When I say "HTML", I mean the HTML (which is, of course, the "original source" of my XML version ... until we succumb to the temptation to start correcting it)

**Comment by DavidHaslam** [comment]
Thanks for clarification. :)
